name: intranet_graneros
description: Intranet para jefes de departamento municipal
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  path_provider: ^2.1.1
  pdf_viewer_plugin: ^2.0.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf
